# ============================================================
# APLICAÇÃO
# ============================================================

spring.application.name=pedidos-spring-api


# ============================================================
# ARQUIVO LOCAL DE VARIÁVEIS
# ============================================================

#spring.config.import=optional:file:.env[.properties]


# ============================================================
# BANCO DE DADOS
# ============================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# ============================================================
# JPA / HIBERNATE
# ============================================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
